//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamilla.Network.Protocols.Wow.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CurrencyTypesNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrencyTypesNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kamilla.Network.Protocols.Wow.Game.CurrencyTypesNames", typeof(CurrencyTypesNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Token Test Token 4.
        /// </summary>
        internal static string Currency1 {
            get {
                return ResourceManager.GetString("Currency1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emblem of Heroism.
        /// </summary>
        internal static string Currency101 {
            get {
                return ResourceManager.GetString("Currency101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emblem of Valor.
        /// </summary>
        internal static string Currency102 {
            get {
                return ResourceManager.GetString("Currency102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena Points.
        /// </summary>
        internal static string Currency103 {
            get {
                return ResourceManager.GetString("Currency103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honor Points DEPRECATED.
        /// </summary>
        internal static string Currency104 {
            get {
                return ResourceManager.GetString("Currency104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterac Valley Mark of Honor.
        /// </summary>
        internal static string Currency121 {
            get {
                return ResourceManager.GetString("Currency121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arathi Basin Mark of Honor.
        /// </summary>
        internal static string Currency122 {
            get {
                return ResourceManager.GetString("Currency122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye of the Storm Mark of Honor.
        /// </summary>
        internal static string Currency123 {
            get {
                return ResourceManager.GetString("Currency123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strand of the Ancients Mark of Honor.
        /// </summary>
        internal static string Currency124 {
            get {
                return ResourceManager.GetString("Currency124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warsong Gulch Mark of Honor.
        /// </summary>
        internal static string Currency125 {
            get {
                return ResourceManager.GetString("Currency125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wintergrasp Mark of Honor.
        /// </summary>
        internal static string Currency126 {
            get {
                return ResourceManager.GetString("Currency126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzzOLDDaily Quest Faction Token.
        /// </summary>
        internal static string Currency141 {
            get {
                return ResourceManager.GetString("Currency141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Keeper&apos;s Shard.
        /// </summary>
        internal static string Currency161 {
            get {
                return ResourceManager.GetString("Currency161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honor Points DEPRECATED2.
        /// </summary>
        internal static string Currency181 {
            get {
                return ResourceManager.GetString("Currency181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Token Test Token 2.
        /// </summary>
        internal static string Currency2 {
            get {
                return ResourceManager.GetString("Currency2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venture Coin.
        /// </summary>
        internal static string Currency201 {
            get {
                return ResourceManager.GetString("Currency201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birmingham Test Item 3.
        /// </summary>
        internal static string Currency22 {
            get {
                return ResourceManager.GetString("Currency22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emblem of Conquest.
        /// </summary>
        internal static string Currency221 {
            get {
                return ResourceManager.GetString("Currency221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champion&apos;s Seal.
        /// </summary>
        internal static string Currency241 {
            get {
                return ResourceManager.GetString("Currency241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emblem of Triumph.
        /// </summary>
        internal static string Currency301 {
            get {
                return ResourceManager.GetString("Currency301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isle of Conquest Mark of Honor.
        /// </summary>
        internal static string Currency321 {
            get {
                return ResourceManager.GetString("Currency321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emblem of Frost.
        /// </summary>
        internal static string Currency341 {
            get {
                return ResourceManager.GetString("Currency341", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrious Jewelcrafter&apos;s Token.
        /// </summary>
        internal static string Currency361 {
            get {
                return ResourceManager.GetString("Currency361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf Archaeology Fragment.
        /// </summary>
        internal static string Currency384 {
            get {
                return ResourceManager.GetString("Currency384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll Archaeology Fragment.
        /// </summary>
        internal static string Currency385 {
            get {
                return ResourceManager.GetString("Currency385", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conquest Points.
        /// </summary>
        internal static string Currency390 {
            get {
                return ResourceManager.GetString("Currency390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tol Barad Commendation.
        /// </summary>
        internal static string Currency391 {
            get {
                return ResourceManager.GetString("Currency391", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honor Points.
        /// </summary>
        internal static string Currency392 {
            get {
                return ResourceManager.GetString("Currency392", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fossil Archaeology Fragment.
        /// </summary>
        internal static string Currency393 {
            get {
                return ResourceManager.GetString("Currency393", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Elf Archaeology Fragment.
        /// </summary>
        internal static string Currency394 {
            get {
                return ResourceManager.GetString("Currency394", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justice Points.
        /// </summary>
        internal static string Currency395 {
            get {
                return ResourceManager.GetString("Currency395", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Points.
        /// </summary>
        internal static string Currency396 {
            get {
                return ResourceManager.GetString("Currency396", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc Archaeology Fragment.
        /// </summary>
        internal static string Currency397 {
            get {
                return ResourceManager.GetString("Currency397", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draenei Archaeology Fragment.
        /// </summary>
        internal static string Currency398 {
            get {
                return ResourceManager.GetString("Currency398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrykul Archaeology Fragment.
        /// </summary>
        internal static string Currency399 {
            get {
                return ResourceManager.GetString("Currency399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Token Test Token 5.
        /// </summary>
        internal static string Currency4 {
            get {
                return ResourceManager.GetString("Currency4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerubian Archaeology Fragment.
        /// </summary>
        internal static string Currency400 {
            get {
                return ResourceManager.GetString("Currency400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tol&apos;vir Archaeology Fragment.
        /// </summary>
        internal static string Currency401 {
            get {
                return ResourceManager.GetString("Currency401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef&apos;s Award.
        /// </summary>
        internal static string Currency402 {
            get {
                return ResourceManager.GetString("Currency402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark of the World Tree.
        /// </summary>
        internal static string Currency416 {
            get {
                return ResourceManager.GetString("Currency416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge of Justice.
        /// </summary>
        internal static string Currency42 {
            get {
                return ResourceManager.GetString("Currency42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conquest Arena Meta.
        /// </summary>
        internal static string Currency483 {
            get {
                return ResourceManager.GetString("Currency483", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conquest BG Meta.
        /// </summary>
        internal static string Currency484 {
            get {
                return ResourceManager.GetString("Currency484", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkmoon Prize Ticket.
        /// </summary>
        internal static string Currency515 {
            get {
                return ResourceManager.GetString("Currency515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalaran Jewelcrafter&apos;s Token.
        /// </summary>
        internal static string Currency61 {
            get {
                return ResourceManager.GetString("Currency61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mote of Darkness.
        /// </summary>
        internal static string Currency614 {
            get {
                return ResourceManager.GetString("Currency614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essence of Corrupted Deathwing.
        /// </summary>
        internal static string Currency615 {
            get {
                return ResourceManager.GetString("Currency615", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalaran Cooking Award.
        /// </summary>
        internal static string Currency81 {
            get {
                return ResourceManager.GetString("Currency81", resourceCulture);
            }
        }
    }
}
