//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamilla.Network.Protocols.Wow.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WowGuidStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WowGuidStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kamilla.Network.Protocols.Wow.Game.WowGuidStrings", typeof(WowGuidStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battlefield Queue.
        /// </summary>
        internal static string BattlefieldQueue {
            get {
                return ResourceManager.GetString("BattlefieldQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpse.
        /// </summary>
        internal static string Corpse {
            get {
                return ResourceManager.GetString("Corpse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature.
        /// </summary>
        internal static string Creature {
            get {
                return ResourceManager.GetString("Creature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicObject.
        /// </summary>
        internal static string DynamicObject {
            get {
                return ResourceManager.GetString("DynamicObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Object.
        /// </summary>
        internal static string GameObject {
            get {
                return ResourceManager.GetString("GameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        internal static string GuidEntry {
            get {
                return ResourceManager.GetString("GuidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({2}, Counter: {0}).
        /// </summary>
        internal static string GuidFormat0 {
            get {
                return ResourceManager.GetString("GuidFormat0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({2}, Counter: {0}, Raw: {3:X16}).
        /// </summary>
        internal static string GuidFormat1 {
            get {
                return ResourceManager.GetString("GuidFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({2}, {4}: {1}, Counter: {0}).
        /// </summary>
        internal static string GuidFormat2 {
            get {
                return ResourceManager.GetString("GuidFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({2}, {4}: {1}, Counter: {0}, Raw: {3:X16}).
        /// </summary>
        internal static string GuidFormat3 {
            get {
                return ResourceManager.GetString("GuidFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Number.
        /// </summary>
        internal static string GuidPetNumber {
            get {
                return ResourceManager.GetString("GuidPetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild.
        /// </summary>
        internal static string Guild {
            get {
                return ResourceManager.GetString("Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Guid).
        /// </summary>
        internal static string NoGuid {
            get {
                return ResourceManager.GetString("NoGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet.
        /// </summary>
        internal static string Pet {
            get {
                return ResourceManager.GetString("Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Transport.
        /// </summary>
        internal static string TransportMo {
            get {
                return ResourceManager.GetString("TransportMo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
    }
}
